# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reala_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('occurred', models.DateTimeField()),
                ('type', models.CharField(max_length=32)),
                ('details', models.CharField(max_length=32)),
                ('notes', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=32)),
                ('phone_verified', models.BooleanField(default=False)),
                ('do_not_contact', models.BooleanField(default=False)),
                ('email_address', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=16)),
                ('notes', models.TextField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='formatted_address',
        ),
        migrations.AddField(
            model_name='parcel',
            name='acres',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='parcel',
            name='assessment',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='parcel',
            name='baths',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='parcel',
            name='beds',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='parcel',
            name='depth',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='parcel',
            name='description',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='parcel',
            name='fireplace',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='parcel',
            name='frontage',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='parcel',
            name='notes',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='parcel',
            name='school',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='parcel',
            name='swis',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='parcel',
            name='year_built',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='lat',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='lon',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='owner',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reala_api.Parcel'),
        ),
        migrations.AddField(
            model_name='event',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reala_api.Parcel'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='contact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reala_api.Owner'),
        ),
    ]
