# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reala_api', '0003_auto_20170403_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='occurred',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='parcel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reala_api.Parcel'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='age',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='email_address',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='gender',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reala_api.Parcel'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='notes',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='acres',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='assessment',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='baths',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='beds',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='depth',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='description',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='fireplace',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='frontage',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='lat',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='lon',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='notes',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='school',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='swis',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='year_built',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
