# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reala_api', '0005_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='parcel',
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reala_api.Owner'),
        ),
    ]
