# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reala_api', '0007_auto_20170407_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='formatted_address',
            field=models.CharField(default='', max_length=128),
        ),
    ]
