# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reala_api', '0008_parcel_formatted_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='lon',
            new_name='lng',
        ),
    ]
