# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reala_api', '0009_auto_20170411_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='formatted_address',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
