# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reala_api', '0011_auto_20170412_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='reala_api.Owner'),
        ),
    ]
